export const ActionTypes = {
  // user
  GET_USER_DETAILS: 'GET_USER_DETAILS',

  // vendors
  GET_ALL_VENDOR: 'GET_ALL_VENDOR',
  ERROR_GETTING_VENDORS: 'ERROR_GETTING_VENDORS',

  // warehouses
  GET_ALL_WAREHOUSES: 'GET_ALL_WAREHOUSES',
  ERROR_GETTING_WAREHOUSES: 'ERROR_GETTING_WAREHOUSES',

  // purchase orders
  GET_ALL_PURCHASEORDERS: 'GET_ALL_PURCHASEORDERS',
  ERROR_GETTING_PURCHASEORDERS: 'ERROR_GETTING_PURCHASEORDERS',
  ADD_PURCHASEORDERS: 'ADD_PURCHASEORDERS',
  PO_VENDORID_FILTER: 'PO_VENDORID_FILTER',
  // INVOICES
  SET_INVOICES: 'SET_INVOICES',

  // products
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
  ERROR_GETTING_PRODUCTS: 'ERROR_GETTING_PRODUCTS',
  GET_ALL_CATEGORIES: 'GET_ALL_CATEGORIES',
  ERROR_GETTING_CATEGORIES: 'ERROR_GETTING_CATEGORIES',
  PRODUCT_NAME_FILTER: 'PRODUCT_NAME_FILTER',
  PRODUCT_CATEGORY_FILTER: 'PRODUCT_CATEGORY_FILTER',
  PRODUCT_ACTIVE_FILTER: 'PRODUCT_ACTIVE_FILTER',
  ADD_PRODUCTS: 'ADD_PRODUCTS',

  // assignments
  GET_ACTIVE_DE: 'GET_ACTIVE_DE',
  ERROR_GET_ACTIVE_DE: 'ERROR_GET_ACTIVE_DE',
  GET_ORDERS: 'GET_ORDERS',
  GET_ZONES: 'GET_ZONES',
  GET_ASSIGNED_ORDERS: 'GET_ASSIGNED_ORDERS',
  GET_ORDER_STATE_SUMMARY: 'GET_ORDER_STATE_SUMMARY',
  SET_SELECTED_ORDERS: 'SET_SELECTED_ORDERS',
  REPLACE_SELECTED_ORDERS: 'REPLACE_SELECTED_ORDERS',
  GET_LOW_STOCK: 'GET_LOW_STOCK',
  GET_ALL_LOW_STOCK: 'GET_ALL_LOW_STOCK',
  SET_ASSIGNMENT_DATE: 'SET_ASSIGNMENT_DATE',
  SET_ASSINGMENT_SLOT: 'SET_ASSINGMENT_SLOT',
  SET_ALL_SLOTS: 'SET_ALL_SLOTS',
  SET_ASSIGNMENT_SLOT_STR: 'SET_ASSIGNMENT_SLOT_STR',
  IS_FETCHING_ASSIGNMENT: 'IS_FETCHING_ASSIGNMENT',
  // banners
  GET_BANNERS: 'GET_BANNERS',

  // customers
  GET_ALL_CUSTOMERS: 'GET_ALL_CUSTOMERS',
  ADD_CUSTOMERS: 'ADD_CUSTOMERS',
  CUSTOMER_FILTER: 'CUSTOMER_FILTER',

  // zones
  GET_ALL_ZONES: 'GET_ALL_ZONES',

  // cod summary
  GET_COD_SUMMARY: 'GET_COD_SUMMARY',
  SET_COD_DATE: 'SET_COD_DATE',

  // partners
  GET_PARTNERS: 'GET_PARTNERS',
  ADD_PARTNERS: 'ADD_PARTNERS',

  // returns and refunds
  GET_RETURNS_AND_REFUNDS: 'GET_RETURNS_AND_REFUNDS',
  ADD_RETURNS_AND_REFUNDS: 'ADD_RETURNS_AND_REFUNDS',
  SET_REFUND_DATE: 'SET_REFUND_DATE',
  SET_DENY_STATE: 'SET_DENY_STATE',

  // estimations
  GET_ESTIMATIONS: 'GET_ESTIMATIONS',
  SET_ESTIMATION_CATEGORY: 'SET_ESTIMATION_CATEGORY',
  SET_ESTIMATION_START_DATE: 'SET_ESTIMATION_START_DATE',
  SET_ESTIMATION_END_DATE: 'SET_ESTIMATION_END_DATE',
  SET_ESTIMATION_SLOT: 'SET_ESTIMATION_SLOT',
};
