export const ActionTypes = {
  // vendors
  GET_ALL_VENDOR: 'GET_ALL_VENDOR',
  ERROR_GETTING_VENDORS: 'ERROR_GETTING_VENDORS',

  // warehouses
  GET_ALL_WAREHOUSES: 'GET_ALL_WAREHOUSES',
  ERROR_GETTING_WAREHOUSES: 'ERROR_GETTING_WAREHOUSES',

  // purchase orders
  GET_ALL_PURCHASEORDERS: 'GET_ALL_PURCHASEORDERS',
  ERROR_GETTING_PURCHASEORDERS: 'ERROR_GETTING_PURCHASEORDERS',

  // products
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
  ERROR_GETTING_PRODUCTS: 'ERROR_GETTING_PRODUCTS',
  GET_ALL_CATEGORIES: 'GET_ALL_CATEGORIES',
  ERROR_GETTING_CATEGORIES: 'ERROR_GETTING_CATEGORIES',
  PRODUCT_NAME_FILTER: 'PRODUCT_NAME_FILTER',
  PRODUCT_CATEGORY_FILTER: 'PRODUCT_CATEGORY_FILTER',
  PRODUCT_ACTIVE_FILTER: 'PRODUCT_ACTIVE_FILTER',
  ADD_PRODUCTS: 'ADD_PRODUCTS',

  // assignments
  GET_ACTIVE_DE: 'GET_ACTIVE_DE',
  ERROR_GET_ACTIVE_DE: 'ERROR_GET_ACTIVE_DE',
  GET_ORDERS: 'GET_ORDERS',
  GET_ZONES: 'GET_ZONES',
  GET_ASSIGNED_ORDERS: 'GET_ASSIGNED_ORDERS',
  GET_ORDER_STATE_SUMMARY: 'GET_ORDER_STATE_SUMMARY',
  SET_SELECTED_ORDERS: 'SET_SELECTED_ORDERS',
  REPLACE_SELECTED_ORDERS: 'REPLACE_SELECTED_ORDERS',
  GET_LOW_STOCK: 'GET_LOW_STOCK',
  GET_ALL_LOW_STOCK: 'GET_ALL_LOW_STOCK',
  SET_ASSIGNMENT_DATE: 'SET_ASSIGNMENT_DATE',
  SET_ASSINGMENT_SLOT: 'SET_ASSINGMENT_SLOT',
  SET_ALL_SLOTS: 'SET_ALL_SLOTS',
  SET_ASSIGNMENT_SLOT_STR: 'SET_ASSIGNMENT_SLOT_STR',
  IS_FETCHING_ASSIGNMENT: 'IS_FETCHING_ASSIGNMENT',
  // banners
  GET_BANNERS: 'GET_BANNERS',
};
