export const ActionTypes = {
  GET_ADMIN: 'GET_ADMIN',
  ERROR_GETTING_ADMIN: 'ERROR_GETTING_ADMIN',
  SET_ADMIN: 'SET_ADMIN',
  ERROR_SETTING_ADMIN: 'ERROR_SETTING_ADMIN',
  GET_ALL_VENDOR: 'GET_ALL_VENDOR',
  ERROR_GETTING_VENDORS: 'ERROR_GETTING_VENDORS',
  GET_ALL_WAREHOUSES: 'GET_ALL_WAREHOUSES',
  ERROR_GETTING_WAREHOUSES: 'ERROR_GETTING_WAREHOUSES',
  GET_ALL_PURCHASEORDERS: 'GET_ALL_PURCHASEORDERS',
  ERROR_GETTING_PURCHASEORDERS: 'ERROR_GETTING_PURCHASEORDERS',
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
  ERROR_GETTING_PRODUCTS: 'ERROR_GETTING_PRODUCTS',
};
